INSERT INTO MoodsVibes (FK_MoodID, FK_VibeID)
VALUES
-- Happy
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Action')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Adventure')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cartoons')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dreaming')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Falling In Love')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Exploring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Music')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Melancholy')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'True Story')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Thought Provoking')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'A Good Laugh')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cheerful')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Touching')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Back To Childhood')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Scaring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Coziness')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dystopia')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Futuristic')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Happy'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Suspense')),

-- Neutral
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Action')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Adventure')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cartoons')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dreaming')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Falling In Love')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Exploring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Melancholy')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'True Story')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Sport')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Mystery')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Traveling')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Motivation')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Escaping')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Coziness')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Thought Provoking')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'A Good Laugh')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cheerful')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Back To Childhood')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Scaring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Suspense')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dystopia')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Futuristic')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Neutral'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Crying')),

-- Sad
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cartoons')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dreaming')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Crying')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Falling In Love')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Exploring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Melancholy')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Calming Down')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Venting')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Nostalgia')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Motivation')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Escaping')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Revenge')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Letting Go')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Tenderness')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Coziness')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Touching')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Back To Childhood')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Cheerful')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Thought Provoking')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Futuristic')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Sad'), (SELECT VibeID FROM Vibes WHERE VibeName = 'True Story')),

-- Angry
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Action')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Adventure')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Sport')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Calming Down')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Venting')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Motivation')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Escaping')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Revenge')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Letting Go')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Tenderness')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Scaring')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Thought Provoking')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Dystopia')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'Futuristic')),
((SELECT MoodID FROM Moods WHERE MoodName = 'Angry'), (SELECT VibeID FROM Vibes WHERE VibeName = 'True Story'));
